### ISSUE TITLE
.lsf files not converting to .lsx even with granny2.dll

### ISSUE THREAD

**Issue by LYNLVL** [ShinyHobo/BG3-Modders-Multitool#103]
I have the granny2.dll within the ExportTool-v1.18-P folder, which I got from 1.15.13.
<img width="623" alt="Screenshot 2023-08-07 135809" src="https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/141603608/54377b4a-6d3f-4f85-ba52-9346536b43d2">

I get receive these types of errors when de-compressing the files:
Note: this is not the initial decompression I did for the unpacked files. When I did do the initial decompression more error lines for lsf. were specifically shown. Lines below only show the .lsbc files (?)
------------------------------------
Retrieving file list for decompression.
Retrived file list. Starting decompression; this could take awhile.
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\Characters_Common_TL_Test.lsbc to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\Characters_Common_TL_Test.lsbs to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\Object_Door.lsbc to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\GlobalFunctions\9271e03f-0ebf-4e79-8973-4485e0b01e13.lsbc to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\Object_Door.lsbs to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\GlobalFunctions\9271e03f-0ebf-4e79-8973-4485e0b01e13.lsbs to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\GlobalFunctions\9cd5fc9a-ade1-47de-93b9-abdd9087e89c.lsbc to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\GlobalFunctions\9cd5fc9a-ade1-47de-93b9-abdd9087e89c.lsbs to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\GlobalFunctions\b58f8c86-48dc-4048-8570-4e6a435de58c.lsbc to .lsx!
Failed to convert C:\Users\user name\Downloads\bg3 modding resources\ExportTool-v1.18-P\UnpackedData\Assets\Public\Shared\Assets\Blueprints\GlobalFunctions\b58f8c86-48dc-4048-8570-4e6a435de58c.lsbs to .lsx!
Decompression complete.

--------------------------------------

As a result gr2 3d models don't appear on the index search and the gameobjectexplorer, and am unable to convert to dae.
![Screenshot (446)](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/141603608/de2046af-7121-4d83-b793-a502fb7c2b0f)

This error shows up even though I do have the granny2.dll file in the folder:
---------------------------------------
[FATAL] Export failed: Granny2.dll is required for compressed GR2 files.
   at LSLib.Native.Granny2Compressor.Decompress4(Byte[] compressed, Int32 decompressedSize)
   at LSLib.Granny.GR2.GR2Reader.UncompressStream()
   at LSLib.Granny.GR2.GR2Reader.Read(Object root)
   at LSLib.Granny.Model.Exporter.LoadGR2(String inPath)
   at LSLib.Granny.Model.Exporter.Export()
   at Divine.CLI.CommandLineGR2Processor.ConvertResource(String file)
Error loading .dae: Filename was null or could not be found. Inner exception: 
-------------------------------------------

**Comment by LYNLVL** [comment]
I hope I did this correctly, I signed up to github to submit this especially as I've seen others with the same issue as me :)

**Comment by Ultraporing** [comment]
Got the same problem. LSLib fails to find the dll despite being a simple LoadLibrary [https://github.com/Norbyte/lslib/blob/fbdf44d4be8c04a9449e9f3763f8b54eca124a4b/LSLibNative/granny2wrapper.cpp#L23](https://github.com/Norbyte/lslib/blob/fbdf44d4be8c04a9449e9f3763f8b54eca124a4b/LSLibNative/granny2wrapper.cpp#L23). Looks to me like a problem stemming from LSLib.

**Comment by LYNLVL** [comment]
I got it to work finally - I re-downloaded everything (lslib, multitool, granny2.dll from 1.15.13) and made sure the granny2.dll was in both the main export tool folder and Tool folder.
