### ISSUE TITLE
Converting map files (bshd?).

### ISSUE THREAD

**Issue by Arco-Dielhof** [ShinyHobo/BG3-Modders-Multitool#104]
I am looking to do something with the map itself. But in order to do anything with it, I need to be able to actually have the map files, PNG, JPG, WEBP all would be fine. Even if they are tiled. Any chance we can get access to those?

I am new to this tool, if they are available but I overlooked them, please feel free to point me in the right direction!

**Comment by Ultraporing** [comment]
https://www.khronos.org/assets/uploads/developers/presentations/BG3_Shaders_Larian.pdf
Here are infos about the format

**Comment by ShinyHobo** [comment]
These files are more than likely inside the virtual textures, for the most part. I recently put out a patch that lets you extract individual gtp files, and I noticed map files among them.
