### ISSUE TITLE
Attempting to copy UUID/Translate String Handle Causes Crash

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#108]
When attempting to copy a UUID/Handle using the software, simply crashes.

Running Windows 10, newest updates.

Newest Version of the multitool and slid, all the other features seem to work fine.

Will attach more info when requested.

**Comment by ShinyHobo** [comment]
Do you mean the application closes when you click the handle field, or does it print something to the console?

**Comment by SoggyBurritoVR** [comment]
Application hard closes, nothing new is added to the console.

**Comment by Ultraporing** [comment]
> 

Do u use some Anti Virus program, besides Windows Defender? I can only think of the possibility, that a zealous Virus Scanner detects the filling of the Clipboard by the tool as harmful. Therefore Kills the process.

**Comment by SoggyBurritoVR** [comment]
I use do use 3rd party avs, I'll try adding the software to exclusions and see if that fixes my issues.

**Comment by SoggyBurritoVR** [comment]
I went ahead and did a test with my 3rd part Avs completely turned off, but the issue persists.

**Comment by Ultraporing** [comment]
> I went ahead and did a test with my 3rd part Avs completely turned off, but the issue persists.
Probably some strange edge case.

I think this is a good reason to implement Crashdumps @ShinyHobo .

**Comment by SoggyBurritoVR** [comment]
Is there a way to see what exactly causes this software to hard close?  A log file maybe?

**Comment by Ultraporing** [comment]
> Is there a way to see what exactly causes this software to hard close? A log file maybe?

Not atm. That's why I suggested putting crash dumps in. I can only imagine it's crashing somewhere within .NET or some 3rd party library.

I'm gonna implement a quick logging to file on crash. And put the build here for you to test.

**Comment by SoggyBurritoVR** [comment]
Sounds great :)

**Comment by Ultraporing** [comment]
Unzip bg3-modders...zip. Then unzip the part2.zip files where the other files are from the first zip file. Had to split them since 25mb upload limit.

Once an exception occurs/crashes, then it should have logged it into "log.txt" in the same folder as the exe.

[bg3-modders-multitool-dev-exlogger.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12326018/bg3-modders-multitool-dev-exlogger.zip)
[part2.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12326022/part2.zip)

**Comment by SoggyBurritoVR** [comment]
[log.txt](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12326028/log.txt)

**Comment by Ultraporing** [comment]
Nice, now i can finally go to sleep and the others can figure out why this happens :).
n8

**Comment by ShinyHobo** [comment]
> Unzip bg3-modders...zip. Then unzip the part2.zip files where the other files are from the first zip file. Had to split them since 25mb upload limit.
> 
> Once an exception occurs/crashes, then it should have logged it into "log.txt" in the same folder as the exe.
> 
> [bg3-modders-multitool-dev-exlogger.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12326018/bg3-modders-multitool-dev-exlogger.zip) [part2.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12326022/part2.zip)

Thanks for working on a crashdump, but as per the the license I have provided (or lack thereof on my project), refrain from distributing derivatives.

**Comment by SoggyBurritoVR** [comment]
Good to know the issue was found, looking forward to any updates :)

**Comment by ShinyHobo** [comment]
> Good to know the issue was found, looking forward to any updates :)

I have made the change suggested by @nandez and published release v0.9.1. Let me know if the problem is not resolved.

**Comment by SoggyBurritoVR** [comment]
Seems to still be crashing with the newest published version.

[log.txt](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12328083/log.txt)

**Comment by ShinyHobo** [comment]
Try this one; I'm thinking the issue is stemming from the clipboard being open by another application somewhere. It should no longer crash on the attempt, but will copy the error to the console window.
[bg3-modders-multitool.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12328124/bg3-modders-multitool.zip)

**Comment by SoggyBurritoVR** [comment]
08/12/2023 23:01:23] Failed to copy to clipboard:
OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at bg3_modders_multitool.ViewModels.MainWindow.CopyGuid(Boolean isHandle)

**Comment by nandez** [comment]
Hey how are you doing? Just by googling the error I found this particular post:

[https://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net](https://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net) 

Seems the error is related to the Win32 API way of handling the clipboard. 

>To set data in the clipboard, you have to [open it](http://msdn.microsoft.com/en-us/library/ms649048(VS.85).aspx) first. Only one process can have the clipboard open at a time. So, when you check, if another process has the clipboard open for any reason, your attempt to open it will fail.

>...working with the clipboard in Win32 is a giant race condition...

Maybe this can help, although the workaround of retrying until success is not fancy, it may be useful in this case.

**Comment by ShinyHobo** [comment]
Yep, I was kind of hoping I wouldn't have to handle it that way, but WPF seems to just be this way. Try this build: 
[bg3-modders-multitool.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12329952/bg3-modders-multitool.zip)

**Comment by SoggyBurritoVR** [comment]
Seems that the issue is gone :)  No errors anymore!
