### ISSUE TITLE
[FeatureRequest] Add functionality to search on string in Index+GameObject explorer (EscapeCharacter/Regex/Wildcards)

### ISSUE THREAD

**Issue by bidaumm** [ShinyHobo/BG3-Modders-Multitool#109]
As per title.. would be extremely useful to be able to search the index and gameobject explorer using expanded search functions.
My understanding currently is that if I search for `new entry "Shout_BladeWard` 
Current functionality is to do a "OR" search for `new` OR `entry` OR `"Shout_Bladeward" and return results.

The biggest feature request would be making it possible to search on `new entry "Shout_BladeWard`  as an entire string.
Followed by searching on wildcards (i.e `new entry "*_BladewWard` 

Or ofc other option would be to add full regex functionality.. 

Apologies if any of these functions are already included. I was struggling to find any info that suggested they did.

**Comment by ShinyHobo** [comment]
The indexer I used, Lucene, does not support this kind of functionality without huge performance losses. I do not intend on supporting this.

**Comment by bidaumm** [comment]
> Edit- I can probably add a secondary search on the returned documents and filter based on the exact text entered, however, wildcards won't be possible due to how the index works, and special characters like quotes are ignored during the process.

Being able to do searches for a complete string would be a huge boon in itself. :)

**Comment by ShinyHobo** [comment]
The way the indexer works does not make this feasible with very large results. Closing for now.

**Comment by ShinyHobo** [comment]
@bidaumm You'll be happy to know that I figured this out today after many, many hours of research. It will be in the next release.

**Comment by ShinyHobo** [comment]
(Mostly) fixed in https://github.com/ShinyHobo/BG3-Modders-Multitool/releases/tag/v0.9.14. Wildcards are unsupported due to already mentioned performance reasons.
