### ISSUE TITLE
Implementing the other ValueList Enums

### ISSUE THREAD

**Issue by Ultraporing** [ShinyHobo/BG3-Modders-Multitool#110]
Hi, I think we should implement the other value List Enums to at least got them together.
I already formatted the file a little. It only needs to be split up, white space between words removed and maybe change the Enum values around to match the existing style. 
I exported stand alone value lists without values as unknown value list file.

Dumped all into this gist, its a bit of work since those are 100+ files.
https://gist.github.com/Ultraporing/58a287bfa483b1548bdc591938391ad1

**Comment by ShinyHobo** [comment]
Be my guest; I already implemented all the required value lists for the GOE.

**Comment by Ultraporing** [comment]
> Be my guest; I already implemented all the required value lists for the GOE.

Done. #111
