### ISSUE TITLE
Game Object Explorer Issue

### ISSUE THREAD

**Issue by Smayt** [ShinyHobo/BG3-Modders-Multitool#117]
Hey i am new to the modding scene and first i had issue compiling the tool becouse while compailing there was a Granny2.DLL missing whie using any object viewer and now when i try to view objects per Game Object Explore i get an error 

i couldn't find a discord or a forum that could help mi solve this issue so i am posting it here 
becouse i habe 0 idea what this eeror means 
help aprriecieted 
BTW thx for the tool eversome job

Stat structure file type 'F:\modding\bg3-modders-multitool\UnpackedData\Shared\Public\Shared\Stats\Generated\Data\CriticalHitTypes.txt' not accounted for.
   bei bg3_modders_multitool.Models.StatStructures.StatStructure.FileType(String file)
   bei bg3_modders_multitool.Services.RootTemplateHelper.ReadData(String pak)
   bei bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__51.MoveNext()

**Comment by ShinyHobo** [comment]
Grab the latest release. This was fixed recently.

**Comment by Smayt** [comment]
this is the latest release

**Comment by Smayt** [comment]
or you mean the Pre-release?

**Comment by ShinyHobo** [comment]
Pre-release; my pre-releases are full releases with debug info turned on.

**Comment by Smayt** [comment]
anyway many thanks its working perfecly now and thanks also for the discord info
