### ISSUE TITLE
Superfluous GR2 files?

### ISSUE THREAD

**Issue by eTzmNcbkrng** [ShinyHobo/BG3-Modders-Multitool#125]
It's my first time making a mod for BG3 so I apologise in advance if this is something mundane, I also hope I'm using the right terminology for what is to come...

There is a mod on Nexus that changes the Initiate die from a D4 to a D20 but it's a loose file (I think).
The mod only requires a single line of text to be changed so it should be simple (again, I think).

I have created my mod folder structure with a single file at `"..\TrueInitiative\Public\Shared\Stats\Generated\Data\TrueInitiative.txt"` this file contains a single line reading `key "InitiativeDie","20"`
I have created a `meta.lsx` with BG3 Mini Tool and place it in `"..\TrueInitiative\Mods\TrueInitiative\meta.lsx"`
In Baldur's Gate 3 Modder's Multitool i have set the path to divine.exe and dragging my workspace in creates my TrueInitiative.zip

The issue: the zip file is 24.5 MB, it contains the `Gustav_Data` folder which, a few layers down has a bunch of GR2 files which seem superfluous. How do I not include these?

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/26512802/f9a617ee-95a5-46ac-bea8-07e84c360ba6)

**Comment by ShinyHobo** [comment]
Remove them from your mod directory. The packing system will only pack files you include in the folder you drag into the packing window. For further assistance, please join the Larian discord.
