### ISSUE TITLE
Blue square not working

### ISSUE THREAD

**Issue by grimbergk** [ShinyHobo/BG3-Modders-Multitool#126]
the blue square when dropping meta, or a .pak or anything from the game files to pak and index, it says: File dropping is not yet supported. Yet all of the tutorial videos on YT and in the discords and on the github show they are. Halp.
![Capture](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/129475789/c88df734-608a-4686-953e-1a07c2e6b722)

**Comment by ShinyHobo** [comment]
It clearly says drop your workspace ie a folder. You cannot drop files into the blue box. Also, your version of the app is out of date.

**Comment by grimbergk** [comment]
ok i tried to download it again but I am not able to locate the exe file inside the zipped after I extract all. I saw it last time I downloaded (the one you said is out of date) please assist one locating the proper exe application to run.
