### ISSUE TITLE
[Question/Suggestion] Batch convert from .lsx to .lsf

### ISSUE THREAD

**Issue by Hasher95** [ShinyHobo/BG3-Modders-Multitool#128]
Hey,
First, thanks for your tool giving to me the opportunity to index and make a search trough the UUID files, it's really helpful.

[Question] 
I was just wondering if we can actually make a batch convert of .LSX files to .LSF files. I'm working on a lot of files and if I understand correctly the only way is, for example to rename each file 0c5e6db6-75cc-4136-ba1c-5605c77a2059.lsf.lsx ? 
Do I have to decompress for the conversion, or do I need to just make my .pak ?

Edit : If something is passing nearby and have the same issue.
Find my way out, I made a script to batch rename all the files in a folder with .lsf at the end before extension and transfer in another one, when you create the .pak all the files are converted to .LSF

[Sugestion]
I don't know if it's even possible or if we already can, but a way to drag & drop into a folder the result files of an index research, or a way to open them all at once.

Another one :
A way to track UUIDs in files searched, sometimes there is parent UUIDs. Can be useful I think.

Thanks again and don’t bother too much with my suggestions, it's just something I was struggling with today but your tool helped already a lot. :)

**Comment by ShinyHobo** [comment]
Naming files .lsf.lsx or .loca.xml will automatically convert them on workspace drop. The repacking procedure creates a converted copy in a temp directory and then packs it for you. You can do other conversions as well, as long as they are supported.

Depending on the UUID, the gameobject explorer does this for you already by sorting parent/child relationships automatically.

**Comment by Hasher95** [comment]
Oh ok, it's good to know. I had no interest in having a 3D previewing so I did not try. Thanks !

**Comment by Hasher95** [comment]
Seems I can't manage to decompress unpacked folders like Models.pak, the tool just don't respond anymore when I do that. Beside that, it's working for .lsf files, or unpacked folders like Shared.pak. I think there is a problem with 3D files, or maybe I have to install a requirement for ?

**Comment by ShinyHobo** [comment]
It takes a really, really long time for decompression to complete (it is absolutely a time issue on some computers). It does not do anything with 3d files; you have to either use the GOE or the index search; those will automatically convert the gr2 files to both dae and fbx, as long as you have granny2.dll from the earlier versions of LSLib.

**Comment by Hasher95** [comment]
Okay thanks I'm going to test this version when I can
I just don't understand because actually the decompression work fine for .lsf and ~1-2GB .pak files, 5-6 minutes and it's done, even if it's actually slower than the tool Norbyte provide it's not a big deal since ID type are correctly converted. But seems like something is blocking the tool at a point...

If the version you provided does the same thing I'm going to try with each subfolders, or .pak one by one, just to see where is the issue

**Comment by ShinyHobo** [comment]
There are a few issues with the latest patch I'm sorting out, one of which was simply crashing out the decompressor. A new version will be uploaded later today.

**Comment by Hasher95** [comment]
Np, going to wait so
Thanks for the updates and for your answers ! :)

**Comment by ShinyHobo** [comment]
I think your issues should be sorted with v0.9.5
