### ISSUE TITLE
Implement localization

### ISSUE THREAD

**Issue by iceriny** [ShinyHobo/BG3-Modders-Multitool#130]
Hey there! 🌸 I was wondering, could we use UUIDs as software string handles to make simple software localization possible? I cloned your project and gave it a little twist for the purpose of, you know, making it work for "Chinese gamers," and it seems to be running pretty smoothly now.

But here's the thing, I'm a bit concerned about the future when you keep updating the software. Since lots of the strings in the UI appear to be hardcoded, maintaining the translated content might become a bit of a puzzle. Do you think we could take a leaf out of BG3's book and use some localization file like XML or maybe Json, to keep our hands on the translation strings?

Thanks a million for your hard work! This tool is seriously a gem. 😊 I just want to double-check, would it be alright if I give my twist a whirl and share it with the Chinese community? Of course, I'd make sure to point everyone straight to your Github page. 🌟

**Comment by ShinyHobo** [comment]
Do not distribute derivative copies of this software; implement I18N (https://learn.microsoft.com/en-us/dotnet/core/extensions/localization). Ie, a collection of key/value pairs in resx files and a translation class to pull the correct pairs given either the locale of the computer or manually selected in a dropdown from the settings dialog. Luckily, the text of the application doesn't change that often.

Each language would need its own .resx file. I use a lot of string formatting to display text in the console window. Luckily you can create key value pairs with {n} and pass them into String.Format (https://stackoverflow.com/a/58445615).

**Comment by ShinyHobo** [comment]
I am very supportive of localization efforts; I work with the Chinese and Ukrainian communities to maintain localization for a bot I made for the Star Citizen community (https://github.com/ShinyHobo/ec-bot/tree/develop/src/translations)

**Comment by ShinyHobo** [comment]
I will take a look at kickstarting this tomorrow.

**Comment by ShinyHobo** [comment]
> Do not distribute derivative copies of this software; fork the project and implement I18N (https://learn.microsoft.com/en-us/dotnet/core/extensions/localization). Ie, a collection of key/value pairs in resx files and a translation class to pull the correct pairs given either the locale of the computer or manually selected in a dropdown from the settings dialog. Luckily, the text of the application doesn't change that often.
> 
> Each language would need its own .resx file. I use a lot of string formatting to display text in the console window. Luckily you can create key value pairs with {n} and pass them into String.Format (https://stackoverflow.com/a/58445615).

The majority of this is complete in my current branch; I am working through adding translation strings to all the UI elements.

**Comment by ShinyHobo** [comment]
@iceriny I have completed the translation work; when you have time, please add your translations and make a pull request. Thanks!

**Comment by iceriny** [comment]
Maybe there's no need to provide translation text functionality, as this involves a question of quickly updating strings through historical translations after a mod version update. This feature is an entirely separate and more independent function, involving various aspects like terminology databases, translation memories, and fuzzy translations. The translation software I'm using currently is Passolo, which is a general-purpose translation tool.

**Comment by iceriny** [comment]
Alrighty then! I'm really heading off to sleep now! Bye-bye! Don't worry if I don't reply next, it's not me giving you the cold shoulder, I promise! 😄

**Comment by iceriny** [comment]
> > This feature is an entirely separate and more independent function, involving various aspects like terminology databases, translation memories, and fuzzy translations. The translation software I'm using currently is Passolo, which is a general-purpose translation tool.
> 
> I made the Multitool to truly be a multitool, providing all the tools people need to make mods. If this is the way it should be done, I would very much like to integrate the workflow to make it easy for people. I have amended the task list.

If you think it's necessary, a complete translation feature should have the following modules:

Terminology Database: This contains a comprehensive collection of in-game nouns as well as user-defined nouns. The software should be able to recognize and tag nouns in strings that need translation. Fortunately, Larian has provided features like Tooltips to mark terms. We can extract nouns and Tooltips strings from localized files. I've written a small extraction program, but it currently uses regular expressions and has some flaws.

Memory Bank: This stores translation histories differentiated by various mods. It should optionally support cross-referencing between different mods to handle expansion content. It can automatically match and fuzzily match untranslated content against historical content, displaying the similarity percentage. For instance, a new string A matches to a string B* with 87% similarity to the original string B, not exactly matching the current source string A, but still matches its translation A*.

Data Export: Ability to export the terminology and memory databases, facilitating collaborative translation.

Comparison Translation: Compare the currently localized XML file with another translated XML file, using UUID matching and string similarity thresholds. If you lack a memory bank but have a translated XML file, you can read the XML you need to translate and use this function to compare it with another XML. It matches corresponding strings when UUIDs match or strings are sufficiently similar.

Search and Replace: Easily find and replace content, possibly supporting regular expressions.

Online Translation: Use APIs from different companies (Google, Baidu, Youdao, Deepl, etc.) for translation. Sometimes, during the initial translation, the online translation feature can be used for pre-translation. However, when using APIs, preprocessing is required, removing Tooltips' tag part and retaining only the text, as API results might be poor otherwise.

These might cover it for now. It's worth noting that all these features should ideally support both all strings and selected strings, as not all situations require processing all the text, just certain parts.

This isn't easy, especially fuzzy matching. The algorithm itself isn't difficult; you can find suitable resources on algorithms like cosine similarity. The challenge lies in doing it quickly. With single-threaded execution, you might need to traverse the entire terminology and memory databases with resource-intensive fuzzy matching for each current string. As the memory bank grows, this could take a lot of time.

This is also why I mentioned that the translation functionality itself might be a larger and more complex module. If you're seriously considering this, it might be worth starting a separate project that's more versatile, supporting translations for various game mods and handling different text formats. Then you can link this multi-functional tool with the translation software, allowing them to exchange data. For example, this tool could unpack mods and have a button to open the translation software, providing the required information for the software to read text and perform other tasks.

**Comment by iceriny** [comment]
Oh, and one more thing! There's an issue with the feature that unpacks the game's .pak files. Right now, it can't locate .pak files for languages other than English.pak. That's because the .pak files for other languages are in subfolders within the Localization folder, and the subfolder names correspond to the language, like for Chinese, it's "Chinese." This means that the localization files for Chinese are located under "Data\Localization\Chinese." Your tool isn't currently searching through all the *.pak files in both the Localization folder and its subfolders.

**Comment by ShinyHobo** [comment]
> Export files into necessary format to be used with external software, such as Passolo
This is all I meant.

The localization pak issue is known and needs to be addressed as part of adding additional languages. It should be relatively trivial to modify the translation grabber service.

**Comment by iceriny** [comment]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/54878570/627c2546-aae3-4f4a-89a1-f8fe28a3620a)
But I only have it in Chinese. However, I think we can use a more general search approach, like scanning through all the subfolders under the Localization directory.





> This is all I meant.

If it's for use with Passolo, then no processing is needed. The Passolo tool is incredibly robust; it's an all-purpose tool that allows custom rules for string recognition – for instance, reading XML formats.

**Comment by ShinyHobo** [comment]
> But I only have it in Chinese. However, I think we can use a more general search approach, like scanning through all the subfolders under the Localization directory.

Agreed; I did not do that because I did not expect there to be further subdirectories.
