### ISSUE TITLE
Add resource quicklinks to toolbar

### ISSUE THREAD

**Issue by ShinyHobo** [ShinyHobo/BG3-Modders-Multitool#146]
Add menu item "Help" with sub-menu "Modding Resources". Directly open each link in the default browser.
- https://github.com/LaughingLeader-DOS2-Mods/LeaderLib/wiki/Lua-Setup 
- https://github.com/Norbyte/bg3se/blob/main/Docs/API.md 
- https://github.com/Norbyte/bg3se/tree/main/SampleMod 
- https://github.com/Norbyte/bg3se/releases
- https://bg3.wiki/wiki/Modding_Resources
- https://github.com/BG3-Community-Library-Team/BG3-Community-Library/wiki
- https://www.nexusmods.com/baldursgate3/mods/1514

**Comment by andrew0030** [comment]
Perhaps have the auto file converter print out information about each file that got converted.
Now I understand that especially with bigger mods this may get messy if there is a lot of files being converted.

That said, maybe having like a simple drop down menu where one can select what information to print would help.
Could perhaps be expanded to function as a "debug level selection", to fine tune the amount and type of console messages.

**Comment by ShinyHobo** [comment]
Added in https://github.com/ShinyHobo/BG3-Modders-Multitool/releases/tag/v0.9.16
