### ISSUE TITLE
Create usage wiki

### ISSUE THREAD

**Issue by ShinyHobo** [ShinyHobo/BG3-Modders-Multitool#150]
The README is quite long, would be a good idea to split it into a user manual in the wiki

**Comment by NellsRelo** [comment]
Planning on writing up some Multitool Documentation over the weekend, will submit what I come up with

**Comment by NellsRelo** [comment]
Forgot to update here, but: [Working Repo](https://github.com/NellsRelo/Multitool-Wiki) for wiki pages, as the .wiki.git faux-repo that git has for wikis doesn't like PRs, this'll be where I'm dumping the files for easy copy/paste into this one.

Things to note:
- So far, Installation, Configuration, and Packaging-Mod-Files is complete
- General-Usage won't be fully complete until the other usage pages are
- Images are currently hosted on Imgur, but would probably want to move them elsewhere at some point
- Links are technically broken on the Working Repo, as they reference what the links will be once brought in

Will update as I flesh them out further

**Comment by NellsRelo** [comment]
Updated the above repo's [wiki](https://github.com/NellsRelo/Multitool-Wiki/wiki) with a Demo wiki of how it can be expected to look like/function.

Just need to finish the GameObject-Explorer, and the main portion will be ready for use. Will likely want add more to explain the Shortcuts and Help menu options, but those are lower priority

**Comment by NellsRelo** [comment]
Aaaaand should be good to go. I've also made some tweaks to the Readme (as seen on the above repo) to shorten it and provide quick access to specific Wiki sections, as well as make it a bit shorter, since most of the information further down is now in pages on the wiki
