### ISSUE TITLE
Am I Dumb? (No exe application?)

### ISSUE THREAD

**Issue by Zealossus** [ShinyHobo/BG3-Modders-Multitool#158]
Title. Can't seem to find the application anywhere. Just all of these extensions and code files

**Comment by ShinyHobo** [comment]
https://github.com/ShinyHobo/BG3-Modders-Multitool/releases

**Comment by Zealossus** [comment]
Thank you!

**Comment by ShinyHobo** [comment]
Join us in the Larian discord if you have other questions: https://discord.com/invite/larianstudios
