### ISSUE TITLE
[Feature Request] Sort/Filter Options for Search Results

### ISSUE THREAD

**Issue by RandoRuda** [ShinyHobo/BG3-Modders-Multitool#160]
When searching I find if there are too many search results that it can be hard to easily parse the data. 

I feel it might help if after we have completed a search that we could possibly sort them in some manner and potentially offer filters based on the results too.

My first thought is sorting/filtering based on file location as an option.

**Comment by ShinyHobo** [comment]
- [ ] Sort results by file path
- [ ] After search, make additional search options available beneath search results
- [ ] File path search filter (contains query)

**Comment by ShinyHobo** [comment]
Added in 0.10.4
