### ISSUE TITLE
String cannot be of zero length.

### ISSUE THREAD

**Issue by Cyberjacket** [ShinyHobo/BG3-Modders-Multitool#165]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/107479092/c1791767-a2ec-48bd-86ed-8243ed2fdc72)
Getting this error when trying to pack a mod.
Is this a bug or did I do something wrong?

**Comment by ShinyHobo** [comment]
Please upload a zip of your workspace so I can debug this more easily. I think the answer is both, and I want the console to be more informative about what went wrong.

**Comment by ShinyHobo** [comment]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/fd553f4d-3fe0-43d0-9b17-72f674818566)
I believe this file requires a .txt extension.

This will be fixed in the next pre-release. Thank you for your patience.
