### ISSUE TITLE
Can not start

### ISSUE THREAD

**Issue by tafeilgh** [ShinyHobo/BG3-Modders-Multitool#168]
An error occurred immediately after clicking bg3-modders-multitool.exe and stopped working.

**Comment by ShinyHobo** [comment]
You need to provide the log file and version number.

**Comment by tafeilgh** [comment]
v0.10.0
Where is the Log file?
Can crashdump be used?

**Comment by ShinyHobo** [comment]
Any specific information you can provide. I can't work with "an error occurred"; I need to know what it was.

**Comment by tafeilgh** [comment]
FIle size is 65mb https://file.io/eUWix0wNxalL

**Comment by ShinyHobo** [comment]
Oh, log.txt should generate in the same folder as the multitool.

**Comment by Extent421** [comment]
I'm seeing this with 0.10.2 as well.  there is no log.txt generated.  If I run from console this is the output

`$ ./bg3-modders-multitool.exe

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at bg3_modders_multitool.Services.GeneralHelper.<>c__DisplayClass0_0.<WriteToConsole>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at bg3_modders_multitool.ViewModels.MainWindow.set_GameDocumentsLocation(String value)
   at bg3_modders_multitool.ViewModels.MainWindow..ctor()
   at bg3_modders_multitool.Views.MainWindow..ctor()
   at LocalizationController.Main()
Segmentation fault
`

**Comment by ShinyHobo** [comment]
@Extent421 Thank you, that helps a lot!

**Comment by Extent421** [comment]
actually the error I'm seeing goes back quite a ways.  The last version that runs correctly for me is 0.9.10.  Starting with 0.9.11 all of them appear to get this segfault

**Comment by ShinyHobo** [comment]
@Extent421 Does it happen with this version?
[bg3-modders-multitool.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12504786/bg3-modders-multitool.zip)

**Comment by Extent421** [comment]
yes, seeing the exact same message

**Comment by ShinyHobo** [comment]
How about this one? I fixed a possible null ref on the console writer. [bg3-modders-multitool.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12504794/bg3-modders-multitool.zip)

**Comment by Extent421** [comment]
same thing

**Comment by ShinyHobo** [comment]
[bg3-modders-multitool.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12504807/bg3-modders-multitool.zip) The error indicates that it is due to a null ref in the writetoconsole function, but I'm already preventing any possible ones from the outside. It seems that the resource file that stores the translations isn't working on your machine. If this version starts, I kind of doubt anything will have text.

Please try it where you have it installed as well as a new location.

**Comment by ShinyHobo** [comment]
[bg3-modders-multitool.zip](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/12504817/bg3-modders-multitool.zip)
I have removed some code in this build that I think might have been throwing it.

**Comment by Extent421** [comment]
both of those two most recent ones work, and I don't see any missing text at first glance

**Comment by ShinyHobo** [comment]
Curious; well I'm glad it works now. I will include the fix in the next release, but feel free to continue using these ones in the meantime. Aside from some text alterations due to it being a working branch, it is functionally identical to 0.10.2.

**Comment by ShinyHobo** [comment]
@tafeilgh try the last version I posted here, please
