### ISSUE TITLE
[Suggestion] Changelog Button

### ISSUE THREAD

**Issue by andrew0030** [ShinyHobo/BG3-Modders-Multitool#169]
So with the latest version (0.10.0) the multitool now has the auto updater.
Looking at the image posted with that version there seems to be a change log when an update is available.
Image:
![7037d928-be5d-44f2-9578-6872a0346b6b](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/36803991/bea076ed-4da3-4089-bbfc-0c3d3df89503)

I looked around for a button to bring up a the change log, but I couldn't find an option to do so, which leads me to believe it only shows up when an update is available?
Perhaps adding a button to look at all the previous changes under the "check for updates" button might be a good idea, as it would allow for users to quickly check if an issue was fixed recently or the version it was fixed in, without opening github.
Maybe something like this:
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/36803991/bbb94e76-b48a-4c4e-832a-36a887396604)
This could also come in handy if a person quickly updates the multitool "skipping" reading the changes, because they want to test something, but would allow them to read the changes later.

**Comment by ShinyHobo** [comment]
Added in 0.10.4
