### ISSUE TITLE
Update possible when indexing

### ISSUE THREAD

**Issue by SwissFred57** [ShinyHobo/BG3-Modders-Multitool#171]
i was indexing Files and i press on Update Available!
then i could update the App but Cancel it because Indexing was not finished and app would close immediately

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/a444dffe-903c-4acc-a63a-c2890b755d1b)

JUst want to report this

**Comment by ShinyHobo** [comment]
Yes, that is intended behavior. Let me know if clicking update doesn't actually update the app.
