### ISSUE TITLE
Game object Explorer not working

### ISSUE THREAD

**Issue by SwissFred57** [ShinyHobo/BG3-Modders-Multitool#172]
I am unable to do an GameObject explorer
i have created an Index prior of this operation

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/45b77be3-ffe4-492c-af5d-898a44a7fcd5)

**Comment by ShinyHobo** [comment]
Can you run the indexer again and make sure it says that it completed, then report back?

**Comment by SwissFred57** [comment]
It Looks like with version 10.0.1 is working

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/f237184f-b9dc-4807-9715-26b53a23a46c)

**Comment by ShinyHobo** [comment]
I think maybe you canceled the index before it finalized, last time. Glad you got it working!
