### ISSUE TITLE
Can not update from 0.10.1 to 0.10.2

### ISSUE THREAD

**Issue by SwissFred57** [ShinyHobo/BG3-Modders-Multitool#173]
i can not update to 0.10.2 update close app and reopens but versin stay at 0.10.1

my folder location C:\Users\xxxxx\Desktop\Moding-Tools\bg3-modders-multitool

Problem was on windows 11 side sorry

**Comment by ShinyHobo** [comment]
Do you have spaces in the xxxxx field you censored? If yes, you need to download 0.10.2 manually.

**Comment by SwissFred57** [comment]
windows uac problem

**Comment by ShinyHobo** [comment]
Running as admin fixed it?

**Comment by SwissFred57** [comment]
Yes as Admin fixed it

**Comment by ShinyHobo** [comment]
Deleted due to valid urls. Thanks for your response
