### ISSUE TITLE
[Feature Request] Resizable main widget

### ISSUE THREAD

**Issue by CamilleHbp** [ShinyHobo/BG3-Modders-Multitool#187]
Would it be possible to make the main UI for the multitool re-sizable? Currently it's the only tool in my BG3 setup that doesn't resize, which means I can't group it with other tools using windows' Snap.

I know it's not critical but if it's something easy to setup could you thing about it? Or would you take a PR? I don't know much about windows forms but I could take a look. It looks like it is not too hard since you only have a few buttons which could stay static, one input which size doesn't matter, and the console output which would actually benefit from being re-sizable.

This is the main UI that I am speaking of.

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/11173924/d75d6547-1c72-47cc-8454-d446a46c1094)

**Comment by ShinyHobo** [comment]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/647e2ee9-0998-4a12-9e95-cc543dadc3b9)
Will be included in 0.10.7
