### ISSUE TITLE
More "word boundaries" for fast search

### ISSUE THREAD

**Issue by xiagu** [ShinyHobo/BG3-Modders-Multitool#188]
It would be very convenient if the "fast" option ignored leading `"` the same way it ignores underscores. This would make searching for UUIDs and other XML attribute values much easier (so you wouldn't have to type `value="...` or whatever attribute name).

**Comment by ShinyHobo** [comment]
Tokenized indexes don't work that way; the index would be 6 times bigger to accomodate this (I tried already). The fast search mode only works because it removes the hidden wildcard at the start of the query text.
