### ISSUE TITLE
Search should either be documented or changed to

### ISSUE THREAD

**Issue by Sairony** [ShinyHobo/BG3-Modders-Multitool#189]
If I put in for example `EndLevel "12"` in the search bar & check .txt only I want to search for exactly that line, instead it searches for all occurrences of either `EndLevel` or `"12"`. Spaces are treated as or sections, which would be fine if you could actually search whole words as well but that doesn't seem to be the case.

**Comment by ShinyHobo** [comment]
It hasn't worked that way for a while. Update your application.

**Comment by ShinyHobo** [comment]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/0e24d229-a88a-4e46-b468-bb4ce37042f0)
