### ISSUE TITLE
Add Open Folder to Index Search

### ISSUE THREAD

**Issue by Sairony** [ShinyHobo/BG3-Modders-Multitool#190]
My .txt files are associated with notepad, which I'm happy with, but I want to open the found files in another editor. Now I must look at the path & navigate there manually from my extracted root. There's also a lot of other cases where one don't want to just straight up open the file in the default editor but have a look at the directory overall.

**Comment by ShinyHobo** [comment]
Associate the .txt format using the properties menu of a file. This is not an application issue. Copy the directory path from the index window.

**Comment by ShinyHobo** [comment]
I will add a directory button in addition to the open button.
