### ISSUE TITLE
[Feature Request] .lsx Concatenation

### ISSUE THREAD

**Issue by NellsRelo** [ShinyHobo/BG3-Modders-Multitool#191]
Back again with another hopefully useful idea: Similar to https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/175, it could be useful to have some level of subfolder support via file concatenation during the packing process for several of the .lsx-focused subfolders. This would especially be handy in reducing file/folder bloat in Progressions, Races, and Root Templates files.

I've set up an [example branch on the Community Library](https://github.com/BG3-Community-Library-Team/BG3-Community-Library/tree/MT-ProgressionsConcatenation) of a potential workspace with this feature in mind.

The idea would be: When packing, Multitool would look at the main children nodes of files in specific directories, parsing through subdirectories as well. For instance, in the `ModName/ActionResourceDefinitions/` folder, a modder could have  `Generic/` and  `Classes/` subfolders. [Using Community Library as an example](https://github.com/BG3-Community-Library-Team/BG3-Community-Library/tree/MT-ProgressionsConcatenation/CommunityLibrary/Public/CommunityLibrary/ActionResourceDefinitions), we have a `Generic/` folder containing `RacialProficiency.ActionResourceDefinitions.lsx`, and a `Classes/DeathKnight/` folder featuring `Spite.ActionResourceDefinitions.lsx` and `DK_Hold.ActionResourceDefinitions.lsx`.

These are, of course, extreme examples, and most mods wouldn't need quite this depth - particularly in Action Resources or ClassDescriptions, where the nodes are small. [Races](https://github.com/BG3-Community-Library-Team/BG3-Community-Library/tree/MT-ProgressionsConcatenation/CommunityLibrary/Public/CommunityLibrary/Races), however, can get pretty sizable, with a single fleshed out Subrace, not counting any parent races, capable of being upwards of 500 lines. [Progressions](https://github.com/BG3-Community-Library-Team/BG3-Community-Library/tree/MT-ProgressionsConcatenation/CommunityLibrary/Public/CommunityLibrary/Progressions) would also benefit, as the moment you start adding progressions for multiple classes or races, things can start to get messy. Similarly, [Root Templates](https://github.com/BG3-Community-Library-Team/BG3-Community-Library/tree/MT-ProgressionsConcatenation/CommunityLibrary/Public/CommunityLibrary/RootTemplates) can become an unreadable mess without a bit of folder structure around it.

In these examples, the mod development side of things become a bit easier to parse. I've set the files as Name.Filename.(lsf.)lsx, in case that would make the process a bit simpler.

The end result workflow would be:
- Mod Folder is supplied to Multitool
- Multitool parses certain subfolders under Public/ModName/ (such as ActionResourceDefinitions, ClassDescriptions, Races, Progressions, and RootTemplates, looking for files within subfolders
- Multitool pushes the nodes in the discovered files, and loads each node into a base template (possibly mod-provided to reduce the need for templates in Multitool) for the expected `.lsx` file (So, Main folder is Progressions = Create Progressions.lsx, RootTemplates could be handled by just moving all template `.lsf.lsx` files into the `RootTemplates/` folder)
- If Needed, convert .lsf.lsx files into .lsf
- Package mod

With the feature being the 2nd and 3rd points in the above process. The key piece would be ensuring that the right file is made for each folder, as the `.lsx` files tend to be more strict on filenames. These usually match the main folder for that portion of the code, which would hopefully simplify this.

**Comment by ShinyHobo** [comment]
Added in 0.11.4
