### ISSUE TITLE
[Feature Request] .git ignore

### ISSUE THREAD

**Issue by neclomant** [ShinyHobo/BG3-Modders-Multitool#192]
Can you make ignoring of directory .git option (or making it by default) when packing mod? Packing doesn't allow pak files without extension as COMMIT_MSG for example.

MyModDirectory
/.git (this)
/Localization
/Mods
/Public

**Comment by ShinyHobo** [comment]
Just move your files into another folder like this: https://github.com/ShinyHobo/PlayableMinotaur
