### ISSUE TITLE
Reapply search index filters on a new search

### ISSUE THREAD

**Issue by OhhLoz** [ShinyHobo/BG3-Modders-Multitool#196]
Hi, I love the tool, thank you so much it's really helpful.
When searching through indexes using filters. each time you make a new search using the same filters they are ignored and instead show all filetype results, meaning for each search you need to open the filter dropdown and force a refresh by changing the filter. It would be great if this happened automatically.
Thanks!

**Comment by ShinyHobo** [comment]
Fixed in 0.10.8
