### ISSUE TITLE
Indicate what as already been unpacked

### ISSUE THREAD

**Issue by mikey10055** [ShinyHobo/BG3-Modders-Multitool#197]
When selecting what .pak files to unpack. ( From the Unpack .pak Files button ) It would be nice to see what has already been unpacked and what has not. 

- [x] Add * next to paks that are detected as having been unpacked to UnpackedData
- [x] Add * disclaimer text above accept/cancel buttons if any paks are detected as being unpacked

**Comment by ShinyHobo** [comment]
Added in 0.10.8
