### ISSUE TITLE
[Feature Request]  'New Mod' 

### ISSUE THREAD

**Issue by laughingowl** [ShinyHobo/BG3-Modders-Multitool#204]
Have multi-tool prompt for ModName (and ideally perhaps a separate folder/root location for created mods (as opposed to downloaded and unpacked)  and the tool lays out the base structure required.  

While perhaps second nature to experienced modders,  I think it would aid considerable new modders that are not 100% sure on what is needed,

**Comment by ShinyHobo** [comment]
- [ ] Add "Create New Mod" button to Utilities menu
- [ ] Ask for meta information (use existing popup), add mod name field (pre-populate new field for existing mods without meta file)
- [ ] Generate basic mod workspace layout in UnpackedMods
- [ ] Open folder to mod workspace

**Comment by ShinyHobo** [comment]
Merged with https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/181
