### ISSUE TITLE
Packing should ignore .git directory

### ISSUE THREAD

**Issue by pavel-kolesnikov** [ShinyHobo/BG3-Modders-Multitool#206]
Hi! Great tool, thank you.

Also, I'd like to version my mod with git.
Git creates `.git` folder.
When `multitool` tries to pack this `.git` directory it hiccups on some 'extensionless' files and fails to pack the mod folder (both for `.pak` and `.zip`).

It'd be good if `multitool` automagically excluded `.git` folder. (Or more broadly: any file\folder which name starts from dot `.`), recursively.
(I'll try to understand the code and provide PR if none fix it before me :D)

**Comment by ShinyHobo** [comment]
Move your workspace into a subdirectory of your git repo.
