### ISSUE TITLE
Auto created meta.lsx using wrong encoding

### ISSUE THREAD

**Issue by merc4derp** [ShinyHobo/BG3-Modders-Multitool#208]
What the title says basically. The meta.lsx produced is using a variation of utf-8 that makes it unreadable. Need to open the file, switch encoding to actual utf-8 and repack to fix it every time.

**Comment by ShinyHobo** [comment]
Switched from UTF-8 BOM to UTF-8. Thanks for the report; it will be fixed in the next release.
