### ISSUE TITLE
granny2.dll is required to convert GR2 files to dae. Please obtain a copy and place it in the sire directory as the application

### ISSUE THREAD

**Issue by Greedboy-55** [ShinyHobo/BG3-Modders-Multitool#209]
Can't open 3d models, get the title as error. I do not have granny2.dll in the directory, and I don't know where to acquire the file,  is there a release that has the dll?

Thanks.
![Capturefaserqwqweqsc](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/77759127/831fa2d3-d533-44fa-9a08-36a467d9efef)

**Comment by ShinyHobo** [comment]
No, you need to find one, as the instructions state. I cannot distribute a copy due to licensing.
