### ISSUE TITLE
Unpacking .PAK isn't unpacking Game Data Folder like before

### ISSUE THREAD

**Issue by Joeyrific** [ShinyHobo/BG3-Modders-Multitool#212]
Multitool isn't unpacking the Game Data folder as it was previously.

Edit: I tried to get this to occur again but I can’t seem to do.
I was previously modifying GR2 file in Blender and just dropping them into the Game Data folder to replace the GR2 I was modifying.
This made it simple to check while the game was running. I could unequip and re-equip the clothing/armor to see the change. 

Now I have to go through the entire .pak process.

**Comment by ShinyHobo** [comment]
I don't understand what you are talking about; no functionality has been removed from the tool. Did you read the patch notes?
