### ISSUE TITLE
[Bug] Stuck on decompressing files

### ISSUE THREAD

**Issue by Fausto1486** [ShinyHobo/BG3-Modders-Multitool#216]
The feature concerning decompressing files (lsf to lsx, etc.) seems to not work after upgrading to the latest version of the tool "0.11.2 - LSLib Updated to 1.18.6".
The CPU isn't doing anything either so it seems that the feature isn't functioning at all.
It's stuck at 0. The GUI thread is not locked but the feature seems to be broken:
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/62660849/2e4be917-20e9-44bf-b6a7-35762d10de92)
I tried deleting the whole unpacked files and unpacked them again but the decompressing feature still doesn't work.
Can someone else replicate the issue?

**Comment by Fausto1486** [comment]
Also "Retrived file list. Starting decompression..." is a typo, should be "Retrieved". Minor issue but you can fix this one together with the others just in case.

**Comment by Fausto1486** [comment]
It seems that this feature also affects the "Convert & Open" option from the index search.
If you try to convert a .lsf to open it, for example, the entire applications crashes.

**Comment by ShinyHobo** [comment]
I cannot reproduce either issue; if you have a log.txt file, please upload it. I need step by step instructions on how to reproduce this from a completely clean state; no one else has reported this issue.

**Comment by Fausto1486** [comment]
I followed your suggestion and re-indexed from scratch.
This time, retrieving the list took longer but when it started the decompression it was still stuck at 0 and wasn't doing anything.
As I type, it is still 0.
Where do I find the log.txt by the way? I can't see in the root folder of the application.

**Comment by Fausto1486** [comment]
Fixed it, the new version of lslib has the file "RconClient.exe" in the folder "tools" which gets flagged as a trojan and deleted silently by Windows Defender. I think this is something which needs to be reported to Norbyte actually but the absence of this file doesn't allow your program to run properly.
