### ISSUE TITLE
[Feature Request] Make folder which is used to unpacking .pak changeable

### ISSUE THREAD

**Issue by LootDust** [ShinyHobo/BG3-Modders-Multitool#222]
When I unpacking 'Gustav.pak', the Temp folder in C disk become totally full so the unpacking failed.
I can't solve this problem because I could hardly pick those unimportant files out to delete.
Is it possible to make the folder which is used to unpacking .pak changeable? Thanks for answering.

**Comment by ShinyHobo** [comment]
Use the unpack game files utility, not the mod  pak unpacker.
