### ISSUE TITLE
after Patch #3 decompressing LSF error

### ISSUE THREAD

**Issue by SwissFred57** [ShinyHobo/BG3-Modders-Multitool#223]
after i load Patch 3 and want to decompress files it tell me LSF version 7 not supported

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/ed45038b-acfb-4344-8664-f72871c7e217)

**Comment by ShinyHobo** [comment]
This is an lslib error; it will be fixed when lslib is updated.

**Comment by ShinyHobo** [comment]
Going to leave open until it is fixed

**Comment by NeatWolf** [comment]
I was looking exactly for this issue: as a side-effect the GameObject Explorer can't properly recreate its index as well

**Comment by ShinyHobo** [comment]
Fixed in 0.11.4
