### ISSUE TITLE
Still getting the bg3.exe issue not found with the latest release

### ISSUE THREAD

**Issue by frellinghazmot** [ShinyHobo/BG3-Modders-Multitool#225]
So I copied over the multitool files into Baldurs Gate3>Bin>Export Tool v1.186 and it says that it can't find bg3.exe and I don't have the option to configure it "*". Is anyone else having this issue or a work around for this? I'm a total noob to the modding community.

Thanks in advance

**Comment by ShinyHobo** [comment]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/2ec46b4a-b1d1-455b-9e42-ab831dfd74df)

**Comment by frellinghazmot** [comment]
Thanks sorry I'm dumb.
