### ISSUE TITLE
Not packing DefaultTheme.Colours.xaml & DefaultTheme.Fonts.xaml

### ISSUE THREAD

**Issue by Nerhak** [ShinyHobo/BG3-Modders-Multitool#228]
Hi,

Merging UI mods, ran into an issue regarding the "Increased Font" mod (https://www.nexusmods.com/baldursgate3/mods/1776)

The mod data structure is:
- \Public\Game\GUI\Theme\DefaultTheme.Colours.xaml
- \Public\Game\GUI\Theme\DefaultTheme.Fonts.xaml
- \Public\Game\GUI\Theme\Scaling\ScaledExtraLarge.xaml
- \Public\Game\GUI\Theme\Scaling\ScaledLarge.xaml
- \Public\Game\GUI\Theme\Scaling\ScaledMedium.xaml
- \Public\Game\GUI\Theme\Scaling\ScaledMinimal.xaml
- \Public\Game\GUI\Theme\Scaling\ScaledSmall.xaml

I could unpak the mod file no problem, but when repacking, the two files 
- \Public\Game\GUI\Theme\DefaultTheme.Colours.xaml
- \Public\Game\GUI\Theme\DefaultTheme.Fonts.xaml

Are absent from the .pak file each time. I suspect it is a regression, possibly on the .Colours.xaml & .Fonts.xaml observed in those files, leading to a wrong parsing stopping at the first extension and, not finding an acceptable extension, stopping ?

**Comment by ShinyHobo** [comment]
I need you to upload a zipped up copy of your workspace; the mod from that nexus page is not a valid pak (missing the Mods folder) and can't be packed.

**Comment by Nerhak** [comment]
-> I do not understand, It is actually packable, since I did it using your software ?
-> Did you fix this by... Not allowing this kind of mod to work ? 
(I understand the modder actually did a poor job and its not working as a pak file, but the issue with the two files being ignored, the real reason I openned this issue, is still there, meaning its still not possible to add the same moddification to a valid mod structure)

**Comment by ShinyHobo** [comment]
I downloaded the pak versions of the mod from the link you provided; they do not have meta.lsx files in them, so are not valid mod paks. This is why I requested that you upload your workspace so I can look at your specific workspace, which you didn't do. I fixed the issue by checking if the conversion is valid, and if not, just copying the file.
