### ISSUE TITLE
Colour Picker Improvement

### ISSUE THREAD

**Issue by Fausto1486** [ShinyHobo/BG3-Modders-Multitool#232]
It could be nice to add an option to paste a colour code that we copy from a RootTemplate file, for example, into the colour picker. This way we can see what kind of colour is used in a specific part of a character/item, and we can recognise elements by using the colours as reference. Not having a Mod Engine, we are stuck on changing colour, load the game, test, close the game, try again.
This improvement could speed up things a little, as we can have a vague idea of what we are looking at in the RootTemplate.

**Comment by ShinyHobo** [comment]
Added in 0.12.10
