### ISSUE TITLE
[Feature Request] .loca.xml  Subfolder Support

### ISSUE THREAD

**Issue by NellsRelo** [ShinyHobo/BG3-Modders-Multitool#249]
It's probably getting a little bit one-note, but, to match the features in Stats/Generated/Data and for several of the `.lsx` folders, I'm wondering if it's doable to have a similar feature for the Localization files. The overall file structure would probably need to be manipulated differently from the `.lsx` files, and just grab every `<content>` tag and its contents, smashing them all into a new `.loca` file in `Localization/{LANGUAGE}` in between `<contentList>` tags.

In the unpacked files, there's a `Localization/{LANGUAGE}/Gender/` subfolder, however it appears to be a path that's checked specifically, as the game doesn't read subfolders, as seen in this [example branch](https://github.com/BG3-Community-Library-Team/BG3-Community-Library/tree/Rework-folder-structure/CommunityLibrary/Localization/English) on the Community Library.

This feature would be useful for keeping localization organized on a per-feature basis. This branch uses familiar game component names, but searching for _any_ subfolder (except perhaps `Gender`* in-case that causes issues), and then merging the contents into a `Localization/{LanguageName}/MT_GEN_ModName_TimeStamp.loca` file during packaging would probably be the way to handle it, as some authors may wish to be more or less specific - I could see localization folders names based on mod version numbers being a thing as well.

**Comment by ShinyHobo** [comment]
Added in 0.12.13
