### ISSUE TITLE
Color Picker Dark Mod

### ISSUE THREAD

**Issue by SwissFred57** [ShinyHobo/BG3-Modders-Multitool#250]
If Color Picker is in Dark mode you can not see R,G,B,A and the Values

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/d21f70ca-948d-4570-81b0-38116f5470be)

could you change the font color to be Black

**Comment by ShinyHobo** [comment]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/0b2fda79-0845-4096-9534-4e3d103c04e5)
I have updated the theme locally and this will be in the next release

**Comment by ShinyHobo** [comment]
Fixed in 0.12.10
