### ISSUE TITLE
[Feature Request] Version Generator

### ISSUE THREAD

**Issue by Ashotep** [ShinyHobo/BG3-Modders-Multitool#251]
Would it be possible to implement a version generator into the tool.  There is something built into BG3 Mod Manager for an example if needed.  Even if it's something similar where you set what version number you want and then copy and paste the (base64?) number into the meta.xml would be appreciated.

In an ideal world you could set the version before you packed up a mod and it would write to the meta.xml file the new number automatically.

Thanks a ton for the awesome tool.

**Comment by ShinyHobo** [comment]
Added in 0.12.10
