### ISSUE TITLE
Color Picker not showing sRGB if i choose a color

### ISSUE THREAD

**Issue by SwissFred57** [ShinyHobo/BG3-Modders-Multitool#257]
i can paste an sRGB in the Preview and it shows the color on the small square
but if i click on a Color it is not shown the sRGB under Preview
example: i put Red sRGB and Click on Blue

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/ea126c8b-742a-494a-ab8e-153e0ac96ce1)

**Comment by ShinyHobo** [comment]
The generated sRGB for that color blue is 0 0 1; I think you might have just missed the 1.
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/98303dd6-9b75-44be-b32d-9536e000ac17)

**Comment by ShinyHobo** [comment]
Actually, is this an issue with the preview not matching the selected color? This is intended behavior; they are different parts of the tool.
