### ISSUE TITLE
Latest update is flagged by windows defender.

### ISSUE THREAD

**Issue by Ashotep** [ShinyHobo/BG3-Modders-Multitool#259]
I'm sure it's a false positive and this is a FYI.  I don't know if your .exe is calling old commands or what.  It's all a bit out of my wheelhouse.  The problem I am now having is that I can't even download the latest update before it gets quarantined despite me giving it the all clear in defender.

[Photo of defender summery](https://photos.app.goo.gl/wzB9EYG9XfkYAWn27)

**Comment by AlfarelSynthesis** [comment]
Can confirm, it's getting flagged as the Bearfoos.B!ml trojan.

**Comment by ShinyHobo** [comment]
I submitted it to microsoft for review; ml means a machine learning filter caught it. If they don't fix it, there isn't really anything I can do. You'd need to turn defender off and add an exception for it.

**Comment by ShinyHobo** [comment]
![Screenshot_20231006-070833_Firefox](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/6206737/e861a105-cbbd-4d36-9961-12f6178a3e8f)
