### ISSUE TITLE
Unable to Update through Wine on Linux

### ISSUE THREAD

**Issue by pipedream420** [ShinyHobo/BG3-Modders-Multitool#260]
As the title says. I'm unable to determine why or see any kind of error messages. It just restarts like it's trying to update, the console window opens and closes in less than a second and then the app restarts without being updated. I wish I could provide logs or something helpful but I've been unable to locate any helpful information so far.

**Comment by ShinyHobo** [comment]
Linux is unsupported. Manually update.
