### ISSUE TITLE
[Feature Request] option to toggle .lsj.lsx creation

### ISSUE THREAD

**Issue by bdsdev** [ShinyHobo/BG3-Modders-Multitool#262]
It's not really the end of the world to have to rollback to using 12.10 and halt updating at the moment, but I've built up a fair bit of personal .lsj json parsing code for studying BG3 innards that 12.12 is no longer generating input for.

**Comment by ShinyHobo** [comment]
This change was not intentional and lsj to lsx forced conversion will be turned off in the next update.

**Comment by ShinyHobo** [comment]
Fixed in 0.12.13
