### ISSUE TITLE
Instant crash on Launch Game

### ISSUE THREAD

**Issue by GawDamnit** [ShinyHobo/BG3-Modders-Multitool#274]
Game instance starts very briefly before crashing. Log attached (though it is very brief).

[gold.2023-10-24T12-38-52-216660.log](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/13126633/gold.2023-10-24T12-38-52-216660.log)

**Comment by ShinyHobo** [comment]
This isn't a multitool issue; it looks like vulkan is crashing on your system.
