### ISSUE TITLE
Unable to Configure LSIB

### ISSUE THREAD

**Issue by redlotus6918** [ShinyHobo/BG3-Modders-Multitool#276]
Am doing initial set-up, but when I open the config window, there is no selection for LSIB location. I've looked through install on both and can't see anything that would direct a resolution. 
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/149549566/7d7930a3-b888-4e1d-b0ce-0e40e36d3533)

**Comment by ShinyHobo** [comment]
Read the wiki.
