### ISSUE TITLE
GamObject Explorer not Display Textures

### ISSUE THREAD

**Issue by HeliumBalloon** [ShinyHobo/BG3-Modders-Multitool#279]
Currently the game objects do not display textures in the 3D Model viewer. I've tried unpacking, uncompressing and indexing the game files I can think of that are relevant, but they still display as white. I've seen at least one[ youtube video](https://www.youtube.com/watch?v=Q3tarnN0YzQ) that show's it display textures, so I've assumed I can do it somehow.

Is it still possible in the current version?

**Comment by ShinyHobo** [comment]
The transition to mostly virtual textures broke this feature a long time ago. I have an issue open for it already (https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/215). Some objects will have textures, but not many.
