### ISSUE TITLE
unpack list not complete

### ISSUE THREAD

**Issue by SwissFred57** [ShinyHobo/BG3-Modders-Multitool#281]
this i see to unpack i scroll down all the way but no Patch Pak

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/c63fa0ae-3eed-4db4-b5e3-e25cf4998c7f)
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/123299068/949e3a95-7589-4f32-9449-d5548b605006)

**Comment by SwissFred57** [comment]
I think they removed all patches PAK in the game

**Comment by ShinyHobo** [comment]
Yes, it looks like they were replaced with PsoCache.pak
