### ISSUE TITLE
Starting game without steam functionality 

### ISSUE THREAD

**Issue by Fausto1486** [ShinyHobo/BG3-Modders-Multitool#283]
Hello there, I noticed that the start game function doesn't work if steam is not launched, however the mod manager allows users to play the game without running steam beforehand. Do you know if this feature can be implemented in the multitool as well?
Bear in mind this is really a secondary thing, I don't mind running steam beforehand but knowing that I can run games directly without running a launcher is a nice thing, it is also straightforward if you're modding.
Also the autoload option is a god sent.

**Comment by ShinyHobo** [comment]
I cannot reproduce this issue; it launches fine for me without Steam running. Ensure that you are on the latest version of the tool.
