### ISSUE TITLE
feel free to close/ Net Framework issues

### ISSUE THREAD

**Issue by LT-Batman** [ShinyHobo/BG3-Modders-Multitool#284]
Im aware that youre unfamiliar with linux systems so I was attempting to rectify the major issue we have myself. Linux users have been unable to use any variation of your tool since 12.0, 11.4 the latest we could use. (regardless of bottles or other wine wrappers)

While browsing the changes from [11.4-12.0 ](https://github.com/ShinyHobo/BG3-Modders-Multitool/compare/v0.11.4...v0.12.0) I fail to see any tinkering whatsoever to dotnet functions, that or im grossly overlooking it. I was wondering if you are aware of any changes you may have made between the two in reference to this part of your tool.

If you care to see one of our debugging processes it does mimic windows when using windows applications. Thank you for your time, and your awesome tool.

**Comment by ShinyHobo** [comment]
Linux is not and will not be supported. I cannot help with this and no specific code changes were made that I am aware of that would break compatibility with wine or bottles. Per the license restrictions I have in place, the application cannot be modified; I suggest running the older version or using a VM.
