### ISSUE TITLE
Packing VFX Mod breaks it since P4 

### ISSUE THREAD

**Issue by ShiveroCodes** [ShinyHobo/BG3-Modders-Multitool#287]
I wanteed to add a new effect to my Database, but realized that nne of the VFX apply anymore after repacking. So i downloaded a working version of my mod from Nexusmods, unpacked and repacked, its also broke, if i throw the unpacked mod directly into my mods folder it justs works. 

Something in the repacking sysem isnt anymore as it was before BG3 Patch 4 which breaks the mod after packing. Try it yourself  https://www.nexusmods.com/baldursgate3/mods/3888

**Comment by ShinyHobo** [comment]
This is almost certainly not a multitool issue. A properly organized workspace will not have issues packing. Please read the wiki or get support from mod makers in the Larian discord.
