### ISSUE TITLE
Error when the Multitool creates a new meta file

### ISSUE THREAD

**Issue by AnxietyTheOrk** [ShinyHobo/BG3-Modders-Multitool#291]
When trying to pack a new mod, using the Multitool to create a new meta file, I am receiving the following error:
Parsing error at or near line 25, column 12:
Input string was not in correct format. 

This error was brought up by another user in the discord.

**Comment by ShinyHobo** [comment]
This is not a multitool error. Your xml is invalid, and the multitool is telling you about it. Please get support from a modder in the Larian discord.

**Comment by SilverBackSpartan** [comment]
The xml is not invalid, this has been going on the past 2 updates, the creation of a new meta.lsx is faulty and doesnt input the version number correctly. Thats line 25 column 12 it's  referring to.

**Comment by ShinyHobo** [comment]
I was given more information in the discord and published a fix for the issue. Without the actual xml to look at, I have to assume that these are simply validation errors, and not unhandled exceptions.
