### ISSUE TITLE
Effects_Banks missing from packaged mod

### ISSUE THREAD

**Issue by dwesslen** [ShinyHobo/BG3-Modders-Multitool#292]
My Echo Knight mod - as released - was packaged with LSLib Toolkit, which works as expected.

When I package it with Modder's Multitool, all the files in Public\DEchoKnight\Assets\Effects\Effects_Banks\Status are omitted.

https://www.nexusmods.com/baldursgate3/mods/3939

**Comment by ShinyHobo** [comment]
Set up your workspace correctly. You can get help with this from other Modders in the Larian discord.
