### ISSUE TITLE
Accessibility: OS Scaling Support

### ISSUE THREAD

**Issue by RandoRuda** [ShinyHobo/BG3-Modders-Multitool#295]
Via The [Larian Discord](https://discord.com/channels/98922182746329088/1172584680470622330)

> Is there a way to have the multitool usable with system UI scaling enabled? I have poor eyesight and a 4k screen, so I have huge system UI scaling turned on, and multitool can't handle this at all. I tried all 3 options under compatibility > High DPI scaling override and it looks the same no matter what I have selected there :/

![Supplied Image](https://media.discordapp.net/attachments/1172584680470622330/1172584680894242826/image.png?ex=6560d995&is=654e6495&hm=e8d8010a7258a8e78f783cc4de1595ccdeec98f4dd7715ddcd69d253edf54a10&=&width=810&height=488)

**Comment by ShinyHobo** [comment]
This would require a heavy rewrite of most UI elements as they are margin pixel based, unfortunately.
