### ISSUE TITLE
Command Line Interface?

### ISSUE THREAD

**Issue by megapatato** [ShinyHobo/BG3-Modders-Multitool#296]
I'm not seeing it documented, and invoking the tool with PowerShell does not show much, so I'm assuming there is no command line interface; apologies if this is incorrect. Concretely, I am looking for functionality for packing a given folder into a given file, e.g.
`$ bg3-modders-multitool.exe -i [input] -o [output] [--to_mods_folder]`

As the tool already has some form of detection for what is dropped into it, there doesn't appear to be a need to specify a `--pack` or `--unpack` flag. Likewise, specifying the file extension (`.pak` vs `.zip`) specifies whether to just package, or also zip with the generated json file. An optional switch `--to_mods_folder` would place the output in the tools pre-configured mods folder. These would reproduce the coarse input/output behavior currently of the tool.

I would consider adding this a good feature, as it would allow me to automate my workflow in programs like VSCode with custom jobs & commands, similar to what can be done for Bethesda games with Pyro and Papyrus Projects.

**Comment by ShinyHobo** [comment]
Use lslib, it has a cli.
