### ISSUE TITLE
Allow specifying vertical frames for Atlas Converter

### ISSUE THREAD

**Issue by PerplexedPeach** [ShinyHobo/BG3-Modders-Multitool#300]
Currently the Atlas Converter allows you to convert from loose frames to a single atlas sheet, but only allows specifying the number of Horizontal Frames to have. It will then add vertical frames as needed when the given vertical frames fill up. This is fine for players who launch in Vulkan because it's able to read non-regular sized atlases, but for players launching in DirectX 11 I believe they will just not see any icons from the atlas. The atlas sizes for them have to be square.

**Comment by ShinyHobo** [comment]
If they have to be square, would it be easier for me to simply make the height and width equal? If you specified a width of 2, but had 40 icons, it would provide an atlas that is mostly empty space to the right, but would stay square with this change. Would that work?

**Comment by PerplexedPeach** [comment]
Yeah in hindsight that's better

**Comment by ShinyHobo** [comment]
I'm told that squares aren't necessary, but have some code set up for implementing this in the future if necessary.
