### ISSUE TITLE
Ignore . folders

### ISSUE THREAD

**Issue by Zehtukae** [ShinyHobo/BG3-Modders-Multitool#301]
I've been using your software and found it very efficient, I am also grateful for the quick fix you did with https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/294. However, it seems directories not related to mods such as .git, .idea, or .vscode directories are being included when copying files to the temporary directory in the `CopyWorkingFilesToTempDir` function, resulting in them being packaged. In my use case, and I assume for most mod creators it would be beneficial to exclude these directories.

I understand that the software's license prohibits direct modification of the codebase, so I'd like to propose a change for your consideration. Here's one potential approach with a modified CopyWorkingFilesToTempDir function:

```
private static void CopyWorkingFilesToTempDir(string path, string modDir)
{
    var ignoreDirs = new[] { ".git", ".idea", ".vscode" };
    var fileList = Directory.GetFiles(path, "*", System.IO.SearchOption.AllDirectories)
                            .Where(file => !ignoreDirs.Any(ignoreDir => new DirectoryInfo(Path.GetDirectoryName(file)).Name.Equals(ignoreDir)))
                            .ToList();

    foreach (var file in fileList)
    {
        var fileName = Path.GetFileName(file);
        var extension = Path.GetExtension(fileName);
        if (!string.IsNullOrEmpty(extension))
        {
            // copy to temp dir
            var fileParent = file.Replace(path, string.Empty);
            var mod = $"{modDir}{fileParent}";
            var modParent = new DirectoryInfo(mod).Parent.FullName;

            // check if matching file for .lsf exists as .lsf.lsx and ignore if yes
            if (new FileInfo(file).Directory.GetFiles(fileName + "*").Length == 1)
            {
                Directory.CreateDirectory(modParent);
                File.Copy(file, mod, true);
            }
        }
    }
}
```

This modification checks if the directory of the current file matches any of the directory names to be ignored. If it does, the file is not included in the fileList. Thank you for considering this change.

**Comment by ShinyHobo** [comment]
Move your workspace into its own directory: https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/206 https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/192

**Comment by ShinyHobo** [comment]
- [ ] Ignore all folders that start with "."

**Comment by ShinyHobo** [comment]
Will be added in v0.12.19
