### ISSUE TITLE
"Build Release" button (Enhancement)

### ISSUE THREAD

**Issue by Syrchalis** [ShinyHobo/BG3-Modders-Multitool#307]
Idea: Next to the "Rebuild" button a button to create a release version.

- Respects "Pack .paks to Mods folder instead of zipping" checkbox (just for consistency)
- Opens a dialogue to change version number
- Dialogue contains four fields that contain the current version from meta.lsx, similar to the field that opens when you first pack a mod that doesn't yet have a meta.lsx (just the fields are populated)
- Fields can be edited and multitool edits the two version numbers in the meta.lsx before packing
- Optionally: Setting in the configuration to automatically increment current version in the above mentioned dialogue (so you just have to click "ok")
- Setting includes the same four fields but instead of typing version number in there you would type how much to increment each field by
- Alternatively just do four checkboxes ("Increment Build", "Increment Revision" etc.)

As example, I tend to increment my releases almost always by 1 in the "Revision" field, unless there is bigger changes. Doing bigger changes manually isnt a big deal, but since I sometimes update mods 5-10 times a day constantly copy-pasting from version calc to meta.lsx gets really tedious.

**Comment by ShinyHobo** [comment]
https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/290
