### ISSUE TITLE
Adding Wildcard characters when searching for Index

### ISSUE THREAD

**Issue by Kensaichi** [ShinyHobo/BG3-Modders-Multitool#308]
Hi, 
This is not an issue, it's just a suggestion but I have no clue how to contact you otherwise :)
Thank you for this amazingly awesome tool for us beginner modders. I would only need 1 more thing to make it the perfect tool.
Being able to use wildcard characters when searching the game index. For example when wanting to find all .anc files related to Jaheira if I simply write "jaheira.anc" it finds only 2 files so its missing most of her .anc files. But if I could search like _*jaheira*_.anc where the * replaces all missing characters in-between it would make my life 10 million times easier. I hope I expressed myself correctly I am kinda new to this and I got this idea from using a lot of WMS and SAP at work where you can easily search for stuff like that :D 
For some reason I can't write * near a word cos it just changes it's format

**Comment by ShinyHobo** [comment]
This has been requested many times, and I have investigated it. It decimates the search time by many magnitudes, so I didn't keep the implementation. Your use case seems like it would be handled by simply searching for jahera and limiting the file type to .anc (using the filetype dropdown to the right of the search bar).

**Comment by Kensaichi** [comment]
Didn't even notice I can do that haha
Shows what a huge expert I am :D 
Thanks a lot and Happy New Year!
