### ISSUE TITLE
Allow customizing/filtering the list of files to be extracted from packs

### ISSUE THREAD

**Issue by Varriount** [ShinyHobo/BG3-Modders-Multitool#309]
Allow customizing/filtering the list of files to be extracted from installed packs. For example, extracting only files that end with `.txt`. The "search index" tool _somewhat_ allows this, however you need to enter a query first in order to get a list of files; you can't' just display all files of a certain type.

**Comment by ShinyHobo** [comment]
A version of this will be in 0.12.21
