### ISSUE TITLE
Unpacking .pak files never complete

### ISSUE THREAD

**Issue by SilverBackSpartan** [ShinyHobo/BG3-Modders-Multitool#313]
when dropping a pak file into the workspace folder the unpacking processes never completes. usually stops at either 5% or 98% forcing a restart of the application.
tried numerous different pak files and the files will be in workspace, but application can no longer be used until re-opened.

The new features are welcomed but is there a way to roll back to the previous version?

**Comment by ShinyHobo** [comment]
You can download 0.12.18 from the release list. This will be fixed in a few hours; sorry for the inconvenience.

**Comment by SilverBackSpartan** [comment]
Thanks for the fast reply Shiny - keep up the great work

**Comment by ShinyHobo** [comment]
Fixed in 0.12.19d
