### ISSUE TITLE
bg3-modders-multitool has stopped working

### ISSUE THREAD

**Issue by swdtech** [ShinyHobo/BG3-Modders-Multitool#320]
![Capture](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/157035629/9601746a-1ec5-43b8-b0f2-b0d74c15d811)
[log.txt](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/13978042/log.txt)

Crashes immediately upon opening the executable, log file is from v 0.9.10 as newer releases did not generate one I could see however the same problem occurs with all versions.

**Comment by swdtech** [comment]
Deleting the config folder doesn't work, executable creates a new one and crashes again.

Windows 7 Professional SP1 x64 no updates.

**Comment by ShinyHobo** [comment]
This doesn't sound like an issue I can fix; as I said, windows 7 is unsupported.
