### ISSUE TITLE
Running Tool using Wine on Mac

### ISSUE THREAD

**Issue by juliandwillett** [ShinyHobo/BG3-Modders-Multitool#321]
I am trying to replicate certain useful functions from the tool for Mac-based execution (the program does not work with Wine, and it would likely take too much on your part even if you were interested to enable this, due to it having issues with the built in terminal commands involved in launch). Can you please provide guidance on how you generated new UUIDs and handles, so I can replicate that?

**Comment by juliandwillett** [comment]
Or perhaps is there a way to execute the program in Linux?

**Comment by juliandwillett** [comment]
Found Linux information

**Comment by ShinyHobo** [comment]
Considering I got it working with Bottles (which uses Wine under the hood), I imagine there is a configuration that must work. I do not own a mac to perform tests with.

In regards to your question about handles, just look at the source code. They are generated with basic Guids and character subsitutions. Please note that this project is not open source, so directly lifting my code for your use is not allowed.

**Comment by ShinyHobo** [comment]
In regards to your original question, the program does not have an auto updater. You must manually trigger the update. It only automatically tells users that an update is available. For users that this feature does not work for, I suggest they simply download the latest release from the release page.

Any terminal commands that run are external to the tool and not used in its normal functions.

**Comment by juliandwillett** [comment]
Understood, thanks. I already produced my own code to make GUIDs and handles (so I will not be using your code). Given that my planned pipeline still relies on producing a PAK file at the end, I'll be sure to direct users to your program, which is a bit more user-friendly in that regard compared to LSLib.
