### ISSUE TITLE
Crash when unpacking mods

### ISSUE THREAD

**Issue by daleao** [ShinyHobo/BG3-Modders-Multitool#322]
Version: 0.12.20c

Trying to unpack any mod crashes the application without any output.
Steps to reproduce:
- Select Utilities -> Unpack mod(s)
- Choose any .pak file

Log: [log.txt](https://github.com/ShinyHobo/BG3-Modders-Multitool/files/14041965/log.txt)

**Comment by ShinyHobo** [comment]
Appears to happen if you don't have a Temp directory created. Will be fixed in 0.12.20d.

**Comment by daleao** [comment]
As a temporary workaround where should I create that dir?
Tried next to the executable but didn't work.
