### ISSUE TITLE
Trojan virus on new update?

### ISSUE THREAD

**Issue by Killasamxx** [ShinyHobo/BG3-Modders-Multitool#326]
Just wondering if this is a false alarm. I did an update on the tool and I got this message stating that there was a virus detected. 

https://ibb.co/VLtVQwP
https://ibb.co/RbqVm9R

Not sure if anyone else had a issue with this but it was concerning to see.

**Comment by ShinyHobo** [comment]
[No](https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/325)
