### ISSUE TITLE
Multitool GameObject Explorer errors

### ISSUE THREAD

**Issue by brenPaidhi** [ShinyHobo/BG3-Modders-Multitool#329]
I am trying to make a very simple mod but keep getting stuck on the GameObjectExporer > Open.  I keep getting an error saying a file is missing or corrupted.  I have verified my game installation but it keeps happening.

**Comment by ShinyHobo** [comment]
https://github.com/ShinyHobo/BG3-Modders-Multitool/wiki/GameObject-Explorer#effective-use-of-the-game-object-explorer

**Comment by ShinyHobo** [comment]
Please try again with version 0.12.22
