### ISSUE TITLE
0.12 broke WINE compatibility

### ISSUE THREAD

**Issue by alterNERDtive** [ShinyHobo/BG3-Modders-Multitool#331]
Just FTR since it came up in Larian Discord. Anything 0.12+ does not start on WINE, or requires footwork I haven’t done :)

**Comment by ShinyHobo** [comment]
I don't support linux at all. I never dide anything with wine, use bottles. https://github.com/ShinyHobo/BG3-Modders-Multitool/wiki/Running-on-Linux

**Comment by ShinyHobo** [comment]
For the record, 0.12.19 is the version I used for the wiki.
