### ISSUE TITLE
XML to Loca conversion doesnt work

### ISSUE THREAD

**Issue by RHodzelmans** [ShinyHobo/BG3-Modders-Multitool#335]
When creating a pack file the tool doesn't convert the <mod>\Localization\English\<whatever>.xml to a loca, leading to missing strings.

**Comment by RHodzelmans** [comment]
Note that you might not want to do this integration and continue to refer to the other Toolkit for that.

**Comment by ShinyHobo** [comment]
This is user error. Please read the wiki on file conversions; xml files are not automatically converted to loca.

**Comment by RHodzelmans** [comment]
Yup, hence I closed it. I completely forgot we have 2 tools for it. Sorry for the noise

**Comment by ShinyHobo** [comment]
> Yup, hence I closed it. I completely forgot we have 2 tools for it. Sorry for the noise

Multitool does convert them if you are explicit about it; use `.loca.xml`. No file conversions happen unless you use this extension format. It is all covered in the wiki.
