### ISSUE TITLE
CLI commands

### ISSUE THREAD

**Issue by riccardo-runci** [ShinyHobo/BG3-Modders-Multitool#337]
Awesome tool, there is a chance to use it with CLI commands on windows? Or with terminal, Thanks!

**Comment by ShinyHobo** [comment]
It is on the list, but is not implemented. Lslib has a cli, so please use it instead if you need it.

**Comment by riccardo-runci** [comment]
> It is on the list, but is not implemented. Lslib has a cli, so please use it instead if you need it.

There is a documentation for CLI commands of LSLib? It support the .zip creation process?

thanks!

**Comment by riccardo-runci** [comment]
> It is on the list, but is not implemented. Lslib has a cli, so please use it instead if you need it.

and what version of lslib are you currenlty using?

thanks

**Comment by ShinyHobo** [comment]
@riccardo-runci as per my license, you are forbidden from modifying my code. Delete your modifications (https://github.com/ShinyHobo/BG3-Modders-Multitool/compare/develop...riccardo-runci:BG3-Modders-Multitool:develop) or I will dmca you.
