### ISSUE TITLE
[Feature Request] Addition of LSLib Toolkit Style Compression on Packing

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#338]
Hello, 

I was wondering if it would be possible to add the Compression methods/selectors that exist in LSLib Toolkit to the Multitool.

Currently, I have been forced to unpack my mods and use LSLib to repack them with higher compression values to save on filespace.  

I mostly use Zlib Optimal, the others such as Zstd don't seem to function well at this time. 

Could possibly be added as part of the main UI next to the Use Compression checkbox (if that does the same thing).

Including image of the specific feature inside LSLib Toolkit 1.19.4:

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/69495940/7b8f6b80-50ec-4a29-a02b-f737edd6e032)

**Comment by ShinyHobo** [comment]
The multitool uses a branch of 1.18.7 to provide functionality, so not all of those options will be available until the 1.19 branch is stable. I can provide the other options; you currently have the options of using LZ4 or no compression.

**Comment by SoggyBurritoVR** [comment]
Would the release version's (1.18.7) **Zlib Optimal** be a possible option?

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/69495940/b53947ef-8744-40d2-9cb5-9c5526ac8320)

**Comment by ShinyHobo** [comment]
Yes, all options available in 1.18.7

**Comment by SoggyBurritoVR** [comment]
That would be perfect!

**Comment by ShinyHobo** [comment]
This will be included in 0.12.27. The feature is complete, but I have another feature that needs to be complete before I can release it.
