### ISSUE TITLE
_merged.lsf.lsx issue

### ISSUE THREAD

**Issue by juliandwillett** [ShinyHobo/BG3-Modders-Multitool#342]
I have been noting an issue when trying to build when using a custom RootTemplate in the Public folder. I got the following error: 

Parsing Error at or near line 8, column 7:
Value cannot be null. (Parameter 's').

The line in for DisplayName with the syntax being correct (there is no issue with the prior line). I have pasted it below.

<?xml version='1.0' encoding='UTF-8'?>
<save>
	<region id="Templates">
		<node id="Templates">
			<children>
				<node id="GameObjects">
					<attribute id="Name" type="LSString" value="Name" />
					<attribute id="DisplayName" type="TranslatedString" handle="hbf709a08g9308g4593g8773ge5dfd1dada02" />
					<attribute id="Description" type="TranslatedString" handle="h6b0d2049gcf63g4c9eg8f1dg901b109406ab" />
					<attribute id="MapKey" type="FixedString" value="0eadec28-a9ce-4dbf-be86-63f58a49b902" />
					<attribute id="ParentTemplateId" type="FixedString" value="569b0f3d-abcd-4b01-aaf0-979091288163" />
					<attribute id="VisualTemplate" type="FixedString" value="ca04fcdc-63c5-85ed-9d4b-eab188289774" />
					<attribute id="Stats" type="FixedString" value="Name" />
					<attribute id="Type" type="FixedString" value="2" />
					<attribute id="_OriginalFileVersion_" type="int64" value="144115207403209022" />
					<attribute id="LevelName" type="FixedString" value="" />
				</node>
			</children>
		</node>
	</region>
</save>

**Comment by ShinyHobo** [comment]
This isn't a multitool issue; your xml is invalid and this is describing exactly which line has the issue. You must have a random 's' in there.

**Comment by juliandwillett** [comment]
The issue was not a random s. There was no "version" parameter in the DisplayName and Description attributes.

<attribute id="DisplayName" type="TranslatedString" handle="h90a30f06g45e7g477dg92c5g381072ec30b1" version="1" />
					<attribute id="Description" type="TranslatedString" handle="hb56ef24eg24a1g46d7gb3a1g44ddaf03a0a2" version="1" />

**Comment by ShinyHobo** [comment]
So, you resolved?

**Comment by juliandwillett** [comment]
Yes, resolved as noted. A version parameter only appears to be essential for "DisplayName" and "Description" attributes, for your or others' reference.
