### ISSUE TITLE
Issue with `.gtp` files

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#344]
![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/69495940/dd6e4e54-40f0-40ea-bbbf-3b4c594e6738)
Albedo_Normal_Physical_0_08d09ede16e

Getting this message when viewing any `.gtp.` file.  Extraction does not function either, messages display normally using the `Extract File` and `Open Folder` but nothing is extracted and shows the following message when using `Extract Selected`.

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/69495940/25d5b0fe-26db-4711-88d3-85923ccb862a)

**Comment by SoggyBurritoVR** [comment]
The issue goes away when downgrading to the `v0.12.27` EXE (all other files untouched).

**Comment by ShinyHobo** [comment]
This will be fixed in 0.13.1
