### ISSUE TITLE
Cannot drop folder/pak since 0.13.x

### ISSUE THREAD

**Issue by Mythalar** [ShinyHobo/BG3-Modders-Multitool#346]
Hey,

I downloaded the last version and set things up again but still cannot drop items to pack/unpack files.

Clicking on the blue left window does allo to select workspace and pack it but I cannot unpack a mod file.

**Comment by ShinyHobo** [comment]
Are you running it in admin mode?

**Comment by Mythalar** [comment]
Yes indeed, switched it and it does work again.
Did not know it could be this.

Thanks =)

**Comment by ShinyHobo** [comment]
Yep, admin mode restricts drag and drop functionality in windows apps. If you need to run it in admin mode, the ability to unpack paks is the first option under the Utilities menu.

**Comment by ShinyHobo** [comment]
I replaced the 0.13.2 release with one with a detection for this issue and a message informing users how to work around it.
