### ISSUE TITLE
[Bug] Launching BG3 with Multitool Causes CTD

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#347]
Using "Lauch Game" causes BG3 to launch, but fully shuts down less than a second later.

The following logs are created inside the Multitool folder on game launch.

`gold.2024-04-05T00-46-42-462929.log`
`network.2024-04-05T00-46-42-460779.log`
`NativeModLoader.log`

Only `NativeModLoader` has any data.

`Failed to get search handle to "NativeMods\*.dll"!`

These logs usually appear inside the `bin` folder inside the BG3 Directory.

**Comment by SoggyBurritoVR** [comment]
Launching the game manually or with the mod manager works and with logs only appearing inside the `bin` folder.

**Comment by ShinyHobo** [comment]
This is not a multitool issue; it only launches the game with or without the command line arguments for quick launching. For both the normal exe and vulkan exe, the game launches as expected for me. I use quick launch and it starts my save for me.

Based on the error, I assume you have Native Mod Loader installed. It is looking for your NativeMods folder relative to your launch location, not relative to the exe, which sounds like a bug with Native Mod Loader.
