### ISSUE TITLE
[Feature Request]  Add ability to Toggle Comment Removal on Packing

### ISSUE THREAD

**Issue by SoggyBurritoVR** [ShinyHobo/BG3-Modders-Multitool#349]
Currently, all comments are removed on packing.

Would it be possible to make this feature toggleable?

Seems it could fit in this area of the configuration window.

![image](https://github.com/ShinyHobo/BG3-Modders-Multitool/assets/69495940/171cbdfc-ba77-4f10-a8c4-f1deb1e2663a)

**Comment by ShinyHobo** [comment]
No, they are removed as a part of the conversion process. It is an engine limitation for the game. Just keep a source repository.
