### ISSUE TITLE
Auto update didn't worked

### ISSUE THREAD

**Issue by Roth1988** [ShinyHobo/BG3-Modders-Multitool#351]
Hey there.

Just to inform, I was using the 0.12.24, and it got a warning about update avaliable (0.13.2d), I choose to update, the app window closed and nothing happand besides the .exe file went from 17MB (i think?) to 180KB, so had to come here download the latest version manualy, which is no "issue" for myself, but I felt I should report the situation though.

thanks for the amazing work

**Comment by ShinyHobo** [comment]
I added a warning to every 0.13.x patch note about this. Please read it next time.
