### ISSUE TITLE
Allow selection of temporary folder in Configuration

### ISSUE THREAD

**Issue by alchemicsoundscape** [ShinyHobo/BG3-Modders-Multitool#354]
Hi there! So my C drive is meant almost exclusively to store OS files and some other (smaller) temp files, and the rest is partitioned out. My small C drive makes running this tool a big headache since its temp files go to the C:\Users\\[currentUser]\AppData\Local\Temp\BG3ModPacker folder. 

It'd be great to be able to select the temp folder location in the Configuration menu, and this would save me a lot of space juggling when trying to extract chunky data.

Additionally it'd be nice if on the "There is not enough space on the disk" error the temp files deleted themselves, as I have to go in manually to remove them every time I see this error.

**Comment by ShinyHobo** [comment]
Hi, I'll take a look at this tomorrow! It shouldn't take me long. If you need it sooner and have the skill, you have permission to open a PR for this.

**Comment by ShinyHobo** [comment]
I merged your PR into my working branch and am doing some touch up work. I'm also adding the auto-delete functionality you asked for.

**Comment by ShinyHobo** [comment]
Added in v0.13.3
