### ISSUE TITLE
Bad symlinks cause crashes when doing index related operations (resolved)

### ISSUE THREAD

**Issue by mazina** [ShinyHobo/BG3-Modders-Multitool#359]
Multitool recently started crashing when trying to do anything related to the index (rebuilding index, decompressing, unpaking, conversion after doing a search).  I eventually figured it out, and I thought I'd report the problem in case you wanted to better handle such scenarios.  

So, it was crashing because there was a bad hard symlink in my Baldurs Gate 3\Data\Localization folder that pointed to a location that no longer existed.  (I think it was from an old, failed attempt to see if I bg3 would reload my mod's loca files when reloading a save.) Removing the symlink eliminated the crashing.

**Comment by ShinyHobo** [comment]
https://github.com/ShinyHobo/BG3-Modders-Multitool/issues/353
