### ISSUE TITLE
All fields and panels go 100% black on mouse-over

### ISSUE THREAD

**Issue by Baraz-Siriel** [ShinyHobo/BG3-Modders-Multitool#361]
First, I realize this issue may not be exclusive to this Multitool and is certainly not caused by it.
BUT I only have that issue with the Multitool and with the new BG3 Toolkit, so it is rather puzzling. 

With both Toolkit and BG3 Modding Multitool (only), when I mouse-over any field or panel (window) in those software, they become entirely black.  I have to resize the window/panel to make them visible again.  It is 100% constant and applies to all secondary panels/windows opened (does not seem to affect the default panels/view shown when opening those two software). 

I have checked various settings in Windows 11, but it is really odd that it happens only in those two software.  It may be a memory issue or GPU issue, but why only with those...  

Any ideas? 

nb: This has nothing to do with any in-game UI.

**Comment by Baraz-Siriel** [comment]
I would select the Help Needed tag here if I know how.

**Comment by ShinyHobo** [comment]
This sounds like a GPU issue; I encounter similar behavior when RDPing into my work desktop running win11 for select programs. Try running it in compatibility mode, I think that is the most help I can provide, especially since you have described it happening with other software.

**Comment by Baraz-Siriel** [comment]
Of ALL the software on a Windows PC, only two tools related to BG3 have this issue. 
That cannot be a coincidence. 
Anyhow, I tried all compatibility tricks : no change.

**Comment by Baraz-Siriel** [comment]
Of ALL the software on my PC, only two tools for BG3 has (had) this issue, so I of course thought it might not be a coincidence... **BUT I found the cause**!  My GPU software (ASUS GPU Tweak III) was tying to apply on Onscreen Display (OSD)... Sigh.
