### ISSUE TITLE
index won't create

### ISSUE THREAD

**Issue by poohwany** [ShinyHobo/BG3-Modders-Multitool#362]
![스크린샷 2024-10-09 225506](https://github.com/user-attachments/assets/a73861e6-6356-48a4-98a0-62f91b9ea3d8)

Whenever I try to create index, the button goes dark grey and it won't create one.

**Comment by ShinyHobo** [comment]
Not enough information for me to help; check that you have followed the installation and configuration steps correctly: https://github.com/ShinyHobo/BG3-Modders-Multitool/wiki/Configuration
