### ISSUE TITLE
Stacktrace when using the GameObject Explorer

### ISSUE THREAD

**Issue by ShinyHobo** [ShinyHobo/BG3-Modders-Multitool#86]
A recent update seems to have broken the GOE. Provided stacktraces have not provided a clue as to a workaround.

**Comment by RHodzelmans** [comment]
GameObjects failed to load. 6,2632815 seconds passed.

The object reference is not set to an instance of an object.
^^^
Translated it states: the objectreferral is not 

   bij bg3_modders_multitool.Models.StatStructures.StatStructure.InheritProperties(String line, List`1 statStructures)
   bij bg3_modders_multitool.Services.RootTemplateHelper.ReadData(String pak)
   bij bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0()
   bij System.Threading.Tasks.Task`1.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__51.MoveNext()

**Comment by RHodzelmans** [comment]
![image](https://user-images.githubusercontent.com/2842380/160207160-1bcbdbd8-73ad-461d-9f05-45fe19eae250.png)
Folder structure of the tool

**Comment by RHodzelmans** [comment]
Unpacked artifacts
![image](https://user-images.githubusercontent.com/2842380/160207222-f412e3ac-d2fa-451d-9e34-c610ce541891.png)

**Comment by RHodzelmans** [comment]
Minotaur
![image](https://user-images.githubusercontent.com/2842380/160207364-8617a45f-4aad-4287-8418-b71cc0bf9bb3.png)

**Comment by RHodzelmans** [comment]
![image](https://user-images.githubusercontent.com/2842380/160207469-97258580-c7c3-4578-b528-9309c2d892be.png)

**Comment by RHodzelmans** [comment]
![image](https://user-images.githubusercontent.com/2842380/160207503-8c3e8670-ca42-4201-a609-1feade067d4b.png)

**Comment by ShinyHobo** [comment]
Fixed in branch goe-hotfix
