### ISSUE TITLE
One or more errors occurred when opening GameObject Explorer 

### ISSUE THREAD

**Issue by Padme4000** [ShinyHobo/BG3-Modders-Multitool#97]
This was the first error.

> One or more errors occurred.
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at bg3_modders_multitool.Services.RootTemplateHelper.ReadRootTemplate()
>    at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__51.MoveNext()

After this I unpacked the files that are required again, reindexed just to make sure it wasn't something that went wrong before. And the above error still came up when loading GameObjectExplorer and waiting for it to load.

**Comment by Jackaroo1432** [comment]
im getting same thing.

**Comment by Jackaroo1432** [comment]
similar issue 

> Loading GameObjects...
> Failed to load english.xml. Please unpack English.pak to generate translations. Skipping...
> Loading CharacterVisualBanks from cache...
> Loading VisualBanks from cache...
> Loading BodySetVisuals from cache...
> Loading MaterialBanks from cache...
> Loading TextureBanks from cache...
> GameObjects failed to load. 17.7518608 seconds passed.
> One or more errors occurred.
> One or more errors occurred.
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at bg3_modders_multitool.Services.RootTemplateHelper.ReadRootTemplate()
>    at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>d__51.MoveNext()


English.pak is also extracted, but for some reason not loading.

**Comment by Ultraporing** [comment]
> similar issue
> 
> > Loading GameObjects...
> > Failed to load english.xml. Please unpack English.pak to generate translations. Skipping...
> > Loading CharacterVisualBanks from cache...
> > Loading VisualBanks from cache...
> > Loading BodySetVisuals from cache...
> > Loading MaterialBanks from cache...
> > Loading TextureBanks from cache...
> > GameObjects failed to load. 17.7518608 seconds passed.
> > One or more errors occurred.
> > One or more errors occurred.
> > at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> > at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
> > at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body) at bg3_modders_multitool.Services.RootTemplateHelper.ReadRootTemplate() at bg3_modders_multitool.Services.RootTemplateHelper.<LoadRootTemplates>b__51_0() at System.Threading.Tasks.Task`1.InnerInvoke()
> > at System.Threading.Tasks.Task.Execute()
> > --- End of stack trace from previous location where exception was thrown ---
> > at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> > at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> > at bg3_modders_multitool.Services.RootTemplateHelper.d__51.MoveNext()
> 
> English.pak is also extracted, but for some reason not loading.

It does not convert the loca files to xml when unpacking/decompressing, so did convert it by hand with "ConverterApp" and it seems to get loaded. Also it throws errors for the "UnpackedData\Shared\Public\Shared\Stats\Generated\Data\CriticalHitTypes.txt" file.
I'm gonna fork the repo and try my hand at fixing the problems.

**Comment by ShinyHobo** [comment]
> > English.pak is also extracted, but for some reason not loading.
> 
> It does not convert the loca files to xml when unpacking/decompressing the English.pak (Localisation). So I did convert it by hand with "ConverterApp" and it seems to get loaded. Also it throws errors for the "UnpackedData\Shared\Public\Shared\Stats\Generated\Data\CriticalHitTypes.txt" file. I'm gonna fork the repo and try my hand at fixing the problems. And gonna limit the max number of threads used for multithreaded operations, gonna add a setting in the options. because there is no need to stress test your cpu and slow everything to a crawl.

LSLib doesn't appear to have loca to xml commandline functionality, so if you plan on doing this, you'll need to make it from scratch.

For the threading issue, I did not add a limit because I wanted the process to go as fast as possible. Assembling the caches for the GOE can take ages. Most modders I talked with fire and forget, so make sure you have an unlimited option for them.

**Comment by Ultraporing** [comment]
> > > English.pak is also extracted, but for some reason not loading.
> > 
> > 
> > It does not convert the loca files to xml when unpacking/decompressing the English.pak (Localisation). So I did convert it by hand with "ConverterApp" and it seems to get loaded. Also it throws errors for the "UnpackedData\Shared\Public\Shared\Stats\Generated\Data\CriticalHitTypes.txt" file. I'm gonna fork the repo and try my hand at fixing the problems. And gonna limit the max number of threads used for multithreaded operations, gonna add a setting in the options. because there is no need to stress test your cpu and slow everything to a crawl.
> 
> LSLib doesn't appear to have loca to xml commandline functionality, so if you plan on doing this, you'll need to make it from scratch.
> 
> For the threading issue, I did not add a limit because I wanted the process to go as fast as possible. Assembling the caches for the GOE can take ages. Most modders I talked with fire and forget, so make sure you have an unlimited option for them.

LSLib got the functionality built in, you just have to call the Methods. Either via linking the dll as reference in your project or just do it via reflection. I just used reflection: https://github.com/ShinyHobo/BG3-Modders-Multitool/commit/7cdbff47608dc6018eee57cdcc5b9d69ce776ca2
As I said not got to test it yet, feel free to test it your self, don't have the time today and tomorrow :).

Regarding the Threads, I intended to put in the recommended 1/2 of your  logical processors as default and up to max num logical processors. I'm worried about the CPU choking the rest of the IO and bus operations if it is permanently on 100% and therefore slow things actually down. It can be that I still live in the olden times xD since this was a thing back in the day.

**Comment by ShinyHobo** [comment]
A shame you did all that work; I'm reworking it to just link the dll. It is automatically converting the loca files when necessary.
